#!/usr/bin/env python3
"""Compose a provenance-verified Wave 1 downstream inventory.

This recovery command is intentionally separate from generation.  It accepts
the accepted checkpoints from a failed full run and one successful source-only
recovery manifest, validates each artifact in its own runtime identity, then
audits and writes a new immutable combined inventory.  The failed run is never
modified and no prompt is regenerated by this module.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Iterable, Mapping

_ROOT = Path(__file__).resolve().parents[1]
_SRC = _ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from construct_benchmark.manifests import file_sha256  # noqa: E402
from construct_benchmark.prompts import PromptRecord, load_prompt_records  # noqa: E402
try:  # direct CLI execution has ``scripts/`` on sys.path; tests use a package import
    from scripts.generate_downstream_prompts import (  # type: ignore
        DEFAULT_MODEL,
        DEFAULT_PROVIDER,
        DEFAULT_REASONING_EFFORT,
        DOWNSTREAM_SPLITS,
        _attempt_usage,
        _atomic_write_json,
        _atomic_write_records,
        _checkpoint_identity,
        _effective_entries,
        _load_checkpoint,
        _load_json_object,
        _reconstruct_spend,
        _validate_downstream_records,
        _validate_quality_gate,
        audit_downstream_inventory,
    )
except ModuleNotFoundError:  # pragma: no cover - exercised by the direct CLI path
    from generate_downstream_prompts import (
        DEFAULT_MODEL,
        DEFAULT_PROVIDER,
        DEFAULT_REASONING_EFFORT,
        DOWNSTREAM_SPLITS,
        _attempt_usage,
        _atomic_write_json,
        _atomic_write_records,
        _checkpoint_identity,
        _effective_entries,
        _load_checkpoint,
        _load_json_object,
        _reconstruct_spend,
        _validate_downstream_records,
        _validate_quality_gate,
        audit_downstream_inventory,
    )


WAVE1_CONSTRUCT_IDS = (
    "realization_account_closure",
    "evidence_diagnosticity",
    "source_reliability",
    "persistence_continuation",
)
DEFAULT_FAILED_RUN_DIR = _ROOT / "results/benchmark/downstream_prompts_v1_wave1_full_luna_v1"
DEFAULT_SOURCE_RECOVERY_DIR = _ROOT / "results/benchmark/downstream_prompts_v1_source_recovery_luna_b20_o30k_v1"
DEFAULT_OUTPUT_DIR = _ROOT / "results/benchmark/downstream_prompts_v1_wave1_full_luna_v1_composed_b20_o30k_v1"
DEFAULT_VECTOR_REFERENCE = _ROOT / "results/benchmark/vector_prompts_v2_luna/full_final_all16/combined.csv"
DEFAULT_QUALITY_GATE = _ROOT / "configs/construct_benchmark/quality_gates/wave1_downstream_luna_composite_v1.json"
DEFAULT_SOURCE_QUALITY_GATE = _ROOT / "configs/construct_benchmark/quality_gates/source_reliability_downstream_luna_recovery_v1.json"


def _canonical_sha256(value: Any) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")
    ).hexdigest()


def _load_object(path: Path, *, label: str) -> dict[str, Any]:
    return _load_json_object(path.resolve(), label=label)


def _require_luna(payload: Mapping[str, Any], *, label: str) -> None:
    if (
        payload.get("provider") not in (None, DEFAULT_PROVIDER)
        or payload.get("requested_model", payload.get("model")) != DEFAULT_MODEL
        or payload.get("reasoning_effort") != DEFAULT_REASONING_EFFORT
    ):
        raise ValueError(f"{label} is not an OpenAI GPT-5.6 Luna xhigh artifact.")
    serialized = json.dumps(payload, sort_keys=True).casefold()
    if "sonnet" in serialized or "claude" in serialized or "openrouter" in serialized:
        raise ValueError(f"{label} contains non-Luna provenance.")


def _require_sha256(value: Any, *, label: str) -> str:
    if (
        not isinstance(value, str)
        or len(value) != 64
        or any(character not in "0123456789abcdef" for character in value.casefold())
    ):
        raise ValueError(f"{label} must be a lowercase SHA-256 string.")
    return value


def _records_equal(left: Iterable[PromptRecord], right: Iterable[PromptRecord]) -> bool:
    return [record.to_mapping() for record in left] == [record.to_mapping() for record in right]


def _checkpoint_attempt_provenance(
    details: Mapping[str, Any],
    *,
    label: str,
) -> dict[str, Any]:
    attempts = details.get("attempts_by_job", {})
    if not isinstance(attempts, Mapping):
        raise ValueError(f"{label} is missing attempts_by_job provenance.")
    for job_id, history in attempts.items():
        if not isinstance(history, list):
            raise ValueError(f"{label} has malformed attempt history for {job_id}.")
        for attempt in history:
            metadata = attempt.get("response_metadata", {})
            if not isinstance(metadata, Mapping):
                raise ValueError(f"{label} has malformed response metadata for {job_id}.")
            if (
                metadata.get("provider") != DEFAULT_PROVIDER
                or metadata.get("model") != DEFAULT_MODEL
                or metadata.get("reasoning_effort") != DEFAULT_REASONING_EFFORT
            ):
                raise ValueError(f"{label} has a non-Luna attempt for {job_id}.")
    usage = _attempt_usage(attempts)
    return {
        "attempt_count": usage["attempt_count"],
        "rejected_attempt_count": usage["rejected_attempt_count"],
        "actual_input_tokens": usage["input_tokens"],
        "actual_output_tokens": usage["output_tokens"],
        "actual_total_tokens": usage["total_tokens"],
        "actual_cost_usd": usage["actual_cost_usd"],
    }


def _validate_recovery_manifest(
    manifest_path: Path,
    *,
    registry_path: Path,
    recovery_batch_size: int,
    recovery_max_output_tokens: int,
    source_quality_gate_path: Path,
    old_source_entry: Any,
    vector_reference: Path | None,
) -> tuple[dict[str, Any], Any, tuple[PromptRecord, ...], dict[str, Any]]:
    manifest_path = manifest_path.resolve()
    manifest = _load_object(manifest_path, label="source recovery manifest")
    _require_luna(manifest, label="source recovery manifest")
    if (
        manifest.get("manifest_type") != "downstream_prompt_generation"
        or manifest.get("status") != "frozen"
        or manifest.get("run_mode") != "full"
        or manifest.get("partial") is not False
        or manifest.get("dry_run") is not False
        or manifest.get("frozen") is not True
        or manifest.get("construct_ids") != ["source_reliability"]
    ):
        raise ValueError("Source recovery manifest must be a frozen source-only full inventory.")
    if int(manifest.get("batch_size", -1)) != recovery_batch_size:
        raise ValueError("Source recovery manifest batch_size does not match the requested recovery identity.")
    runtime_settings = manifest.get("runtime_settings")
    if not isinstance(runtime_settings, Mapping):
        raise ValueError("Source recovery manifest is missing runtime_settings.")
    if int(runtime_settings.get("max_output_tokens", -1)) != recovery_max_output_tokens:
        raise ValueError("Source recovery manifest max_output_tokens does not match the requested recovery identity.")
    input_price = runtime_settings.get("input_usd_per_million_tokens")
    output_price = runtime_settings.get("output_usd_per_million_tokens")
    if not isinstance(input_price, (int, float)) or not isinstance(output_price, (int, float)):
        raise ValueError("Source recovery manifest lacks explicit token prices.")

    recovery_entries = _effective_entries(
        registry_path,
        waves=[1],
        construct_ids=["source_reliability"],
        batch_size=recovery_batch_size,
        max_output_tokens=recovery_max_output_tokens,
        model=DEFAULT_MODEL,
    )
    recovery_entry = recovery_entries[0]
    constructs = manifest.get("constructs")
    if not isinstance(constructs, list) or len(constructs) != 1 or not isinstance(constructs[0], Mapping):
        raise ValueError("Source recovery manifest must contain exactly one construct manifest.")
    item = dict(constructs[0])
    if item.get("construct_id") != "source_reliability":
        raise ValueError("Source recovery manifest contains the wrong construct.")
    for field_name, expected in (
        ("source_plan_sha256", recovery_entry.source_plan_sha256),
        ("plan_sha256", recovery_entry.plan_sha256),
        ("spec_sha256", recovery_entry.spec_sha256),
    ):
        if item.get(field_name) != expected:
            raise ValueError(f"Source recovery manifest has a stale {field_name}.")
    output_value = item.get("output_path")
    output_hash = _require_sha256(item.get("output_sha256"), label="source recovery output_sha256")
    if not isinstance(output_value, str) or not output_value.strip():
        raise ValueError("Source recovery manifest lacks an output_path.")
    output_path = Path(output_value).resolve()
    if not output_path.exists() or file_sha256(output_path) != output_hash:
        raise ValueError("Source recovery output hash mismatch.")
    records = tuple(load_prompt_records(output_path))
    details = _validate_downstream_records(
        recovery_entry,
        records,
        mode="full",
        input_price=float(input_price),
        output_price=float(output_price),
    )
    if item.get("record_count") != details["record_count"] or item.get("split_counts") != details["split_counts"]:
        raise ValueError("Source recovery construct counts do not match its output.")
    expected_counts = manifest.get("counts", {})
    if (
        expected_counts.get("record_count") != 96
        or expected_counts.get("split_counts") != {
            "behavior_eval": 32,
            "calibration": 32,
            "steering_eval": 32,
        }
    ):
        raise ValueError("Source recovery manifest does not report the exact 96-record schedule.")
    combined_value = manifest.get("combined_path")
    combined_hash = _require_sha256(manifest.get("combined_sha256"), label="source recovery combined_sha256")
    if not isinstance(combined_value, str) or file_sha256(Path(combined_value).resolve()) != combined_hash:
        raise ValueError("Source recovery combined output hash mismatch.")
    combined_records = tuple(load_prompt_records(Path(combined_value).resolve()))
    if not _records_equal(combined_records, records):
        raise ValueError("Source recovery combined.csv differs from its construct output.")
    recovery_audit = manifest.get("audit")
    if not isinstance(recovery_audit, Mapping) or recovery_audit.get("severe_flag_count") != 0 or recovery_audit.get("passed") is not True:
        raise ValueError("Source recovery manifest is not backed by a passing audit.")
    if vector_reference is not None:
        if recovery_audit.get("vector_reference_path") != str(vector_reference.resolve()):
            raise ValueError("Source recovery audit used a different vector reference.")
        if int(recovery_audit.get("vector_reference_record_count", 0)) <= 0:
            raise ValueError("Source recovery audit does not include the vector reference inventory.")

    if not source_quality_gate_path.exists():
        raise ValueError(f"Source-only quality gate does not exist: {source_quality_gate_path}")
    source_gate = _validate_quality_gate(source_quality_gate_path, [old_source_entry])
    recovery_quality_gate = manifest.get("quality_gate")
    if not isinstance(recovery_quality_gate, Mapping) or recovery_quality_gate.get("approved") is not True:
        raise ValueError("Source recovery manifest lacks an approved source-only quality gate.")
    gate_path_value = recovery_quality_gate.get("quality_gate_path")
    if isinstance(gate_path_value, str) and Path(gate_path_value).resolve() != source_quality_gate_path.resolve():
        raise ValueError("Source recovery manifest points to a different quality gate than requested.")

    return manifest, recovery_entry, records, {
        "details": details,
        "construct_manifest": item,
        "quality_gate": source_gate,
        "manifest_sha256": file_sha256(manifest_path),
        "manifest_path": str(manifest_path),
        "output_path": str(output_path),
        "output_sha256": output_hash,
        "combined_sha256": combined_hash,
    }


def compose_downstream_inventory(
    *,
    registry_path: str | Path = _ROOT / "configs/construct_benchmark/construct_registry_v1.json",
    failed_run_dir: str | Path = DEFAULT_FAILED_RUN_DIR,
    source_recovery_dir: str | Path = DEFAULT_SOURCE_RECOVERY_DIR,
    output_dir: str | Path = DEFAULT_OUTPUT_DIR,
    vector_reference: str | Path | None = DEFAULT_VECTOR_REFERENCE,
    quality_gate_file: str | Path = DEFAULT_QUALITY_GATE,
    source_quality_gate_file: str | Path = DEFAULT_SOURCE_QUALITY_GATE,
    old_batch_size: int = 20,
    old_max_output_tokens: int = 12_000,
    recovery_batch_size: int = 20,
    recovery_max_output_tokens: int = 30_000,
    expected_checkpoint_sha256: Mapping[str, str] | None = None,
    expected_source_recovery_manifest_sha256: str | None = None,
) -> dict[str, Any]:
    """Compose a complete Wave 1 inventory without issuing API requests."""

    registry_path = Path(registry_path).resolve()
    failed_root = Path(failed_run_dir).resolve()
    source_root = Path(source_recovery_dir).resolve()
    output_root = Path(output_dir).resolve()
    vector_path = None if vector_reference is None else Path(vector_reference).resolve()
    quality_gate_path = Path(quality_gate_file).resolve()
    source_quality_gate_path = Path(source_quality_gate_file).resolve()
    if output_root.exists() and any(output_root.iterdir()):
        raise FileExistsError(f"Refusing to overwrite non-empty composition output: {output_root}")
    if old_batch_size < 1 or old_max_output_tokens < 1 or recovery_batch_size < 1 or recovery_max_output_tokens < 1:
        raise ValueError("Batch sizes and output-token limits must be positive.")
    if vector_path is not None and not vector_path.exists():
        raise ValueError(f"Vector reference inventory does not exist: {vector_path}")

    old_entries = _effective_entries(
        registry_path,
        waves=[1],
        construct_ids=list(WAVE1_CONSTRUCT_IDS),
        batch_size=old_batch_size,
        max_output_tokens=old_max_output_tokens,
        model=DEFAULT_MODEL,
    )
    old_by_id = {entry.construct_id: entry for entry in old_entries}
    if set(old_by_id) != set(WAVE1_CONSTRUCT_IDS):
        raise ValueError("The failed artifact set is not exactly Wave 1.")
    _validate_quality_gate(quality_gate_path, old_entries)

    run_state_path = failed_root / "downstream_prompt_run_state.json"
    failed_state = _load_object(run_state_path, label="failed downstream run state")
    _require_luna(failed_state.get("run_identity", {}), label="failed downstream run identity")
    if failed_state.get("status") != "failed":
        raise ValueError("The source run directory must be a failed, non-frozen run.")
    run_identity = failed_state.get("run_identity")
    if not isinstance(run_identity, Mapping):
        raise ValueError("Failed run state lacks run_identity.")
    if run_identity.get("construct_ids") != list(WAVE1_CONSTRUCT_IDS):
        raise ValueError("Failed run state does not cover exactly the four Wave 1 constructs.")
    runtime_settings = run_identity.get("runtime_settings")
    if not isinstance(runtime_settings, Mapping):
        raise ValueError("Failed run identity lacks runtime_settings.")
    if (
        int(runtime_settings.get("batch_size", -1)) != old_batch_size
        or int(runtime_settings.get("max_output_tokens", -1)) != old_max_output_tokens
    ):
        raise ValueError("Failed run runtime settings do not match the pinned checkpoint identity.")
    if run_identity.get("provider") != DEFAULT_PROVIDER or run_identity.get("model") != DEFAULT_MODEL or run_identity.get("reasoning_effort") != DEFAULT_REASONING_EFFORT:
        raise ValueError("Failed run identity is not Luna-only.")

    completed_ids = set(failed_state.get("completed_construct_ids", []))
    expected_completed = set(WAVE1_CONSTRUCT_IDS) - {"source_reliability"}
    if completed_ids != expected_completed:
        raise ValueError(f"Failed run completed IDs are not exactly {sorted(expected_completed)}.")

    records_by_construct: dict[str, tuple[PromptRecord, ...]] = {}
    checkpoint_provenance: dict[str, dict[str, Any]] = {}
    checkpoint_usage_maps: dict[str, dict[str, list[dict[str, Any]]]] = {}
    checkpoint_hashes = dict(expected_checkpoint_sha256 or {})
    for construct_id in WAVE1_CONSTRUCT_IDS:
        entry = old_by_id[construct_id]
        checkpoint_path = failed_root / "checkpoints" / f"{construct_id}.json"
        if not checkpoint_path.exists():
            raise ValueError(f"Missing failed-run checkpoint for {construct_id}: {checkpoint_path}")
        checkpoint_hash = file_sha256(checkpoint_path)
        expected_hash = checkpoint_hashes.get(construct_id)
        if expected_hash is not None and checkpoint_hash != _require_sha256(expected_hash, label=f"{construct_id} checkpoint hash"):
            raise ValueError(f"Checkpoint hash mismatch for {construct_id}.")
        identity = _checkpoint_identity(entry, run_identity)
        recovered, _metadata, checkpoint_details = _load_checkpoint(
            checkpoint_path,
            entry=entry,
            identity=identity,
            mode="full",
        )
        records = tuple(record for job_id in sorted(recovered) for record in recovered[job_id])
        checkpoint_usage_maps[construct_id] = dict(checkpoint_details["attempts_by_job"])
        attempt_provenance = _checkpoint_attempt_provenance(
            checkpoint_details,
            label=f"{construct_id} checkpoint",
        )
        if construct_id == "source_reliability":
            if records or attempt_provenance["rejected_attempt_count"] != attempt_provenance["attempt_count"]:
                raise ValueError("Failed source checkpoint contains materialized or accepted records.")
        else:
            if not records:
                raise ValueError(f"Completed checkpoint for {construct_id} is empty.")
            details = _validate_downstream_records(
                entry,
                records,
                mode="full",
                input_price=float(runtime_settings.get("input_usd_per_million_tokens", 0.2)),
                output_price=float(runtime_settings.get("output_usd_per_million_tokens", 1.2)),
            )
            expected = {
                "realization_account_closure": 36,
                "evidence_diagnosticity": 54,
                "persistence_continuation": 24,
            }[construct_id]
            if details["record_count"] != expected:
                raise ValueError(f"{construct_id} checkpoint has {details['record_count']} records; expected {expected}.")
            records_by_construct[construct_id] = records
        checkpoint_provenance[construct_id] = {
            "path": str(checkpoint_path),
            "file_sha256": checkpoint_hash,
            "internal_checksum_sha256": _load_object(checkpoint_path, label=f"{construct_id} checkpoint").get("checksum_sha256"),
            "source_plan_sha256": entry.source_plan_sha256,
            "effective_plan_sha256": entry.plan_sha256,
            "record_count": len(records),
            "job_count": checkpoint_details["checkpoint_job_count"],
            "attempt_count": attempt_provenance["attempt_count"],
            "rejected_attempt_count": attempt_provenance["rejected_attempt_count"],
            "actual_input_tokens": attempt_provenance["actual_input_tokens"],
            "actual_output_tokens": attempt_provenance["actual_output_tokens"],
            "actual_total_tokens": attempt_provenance["actual_total_tokens"],
            "actual_cost_usd": attempt_provenance["actual_cost_usd"],
        }

    checkpoint_attempts = {
        job_id: history
        for histories in checkpoint_usage_maps.values()
        for job_id, history in histories.items()
    }
    failed_usage = _attempt_usage(checkpoint_attempts)
    for field, state_field in (
        ("attempt_count", "cumulative_attempt_count"),
        ("rejected_attempt_count", "cumulative_rejected_attempt_count"),
        ("input_tokens", "cumulative_actual_input_tokens"),
        ("output_tokens", "cumulative_actual_output_tokens"),
        ("total_tokens", "cumulative_actual_total_tokens"),
    ):
        if int(failed_usage[field]) != int(failed_state.get(state_field, -1)):
            raise ValueError(f"Failed run state {state_field} disagrees with checkpoint attempt history.")
    if abs(float(failed_usage["actual_cost_usd"]) - float(failed_state.get("cumulative_actual_spent_usd", -1.0))) > 1e-12:
        raise ValueError("Failed run state spend disagrees with checkpoint attempt history.")
    run_state_hash = file_sha256(run_state_path)

    source_manifest_path = source_root / "final_inventory_manifest.json"
    source_manifest, recovery_entry, source_records, recovery_info = _validate_recovery_manifest(
        source_manifest_path,
        registry_path=registry_path,
        recovery_batch_size=recovery_batch_size,
        recovery_max_output_tokens=recovery_max_output_tokens,
        source_quality_gate_path=source_quality_gate_path,
        old_source_entry=old_by_id["source_reliability"],
        vector_reference=vector_path,
    )
    records_by_construct["source_reliability"] = source_records

    all_records: list[PromptRecord] = []
    for construct_id in WAVE1_CONSTRUCT_IDS:
        all_records.extend(records_by_construct[construct_id])
    if len(all_records) != 210:
        raise ValueError(f"Composed inventory has {len(all_records)} records; expected 210.")
    split_counts = {
        split: sum(record.split == split for record in all_records)
        for split in sorted(DOWNSTREAM_SPLITS)
    }
    if split_counts != {"behavior_eval": 70, "calibration": 70, "steering_eval": 70}:
        raise ValueError(f"Composed split counts are not exact: {split_counts}.")

    # The plan/runtime hash for source is allowed to differ because the source
    # recovery deliberately uses a smaller request batch.  Each construct is
    # validated against the exact effective plan under which its rows were
    # accepted before the combined audit is run.
    _validate_downstream_records(
        recovery_entry,
        source_records,
        mode="full",
        input_price=float(source_manifest["runtime_settings"]["input_usd_per_million_tokens"]),
        output_price=float(source_manifest["runtime_settings"]["output_usd_per_million_tokens"]),
    )
    audit = audit_downstream_inventory(all_records, old_entries, vector_reference=vector_path)
    if not audit["passed"]:
        raise ValueError(
            f"Composition audit failed with {audit['severe_flag_count']} severe flag(s): "
            + json.dumps(audit["flags"], sort_keys=True)
        )

    source_accounting = source_manifest.get("accounting", {})
    if not isinstance(source_accounting, Mapping):
        raise ValueError("Source recovery manifest lacks accounting provenance.")
    source_attempt_count = int(source_accounting.get("cumulative_attempt_count", source_manifest["counts"].get("attempt_count", 0)))
    source_rejected_count = int(source_accounting.get("cumulative_rejected_attempt_count", source_manifest["counts"].get("rejected_attempt_count", 0)))
    source_failed_count = int(source_accounting.get("cumulative_failed_request_count", source_manifest["counts"].get("failed_request_count", 0)))
    source_input_tokens = int(source_accounting.get("cumulative_actual_input_tokens", source_manifest["counts"].get("actual_input_tokens", 0)))
    source_output_tokens = int(source_accounting.get("cumulative_actual_output_tokens", source_manifest["counts"].get("actual_output_tokens", 0)))
    source_total_tokens = int(source_accounting.get("cumulative_actual_total_tokens", source_manifest["counts"].get("actual_total_tokens", 0)))
    source_spend = float(source_accounting.get("cumulative_actual_spent_usd", source_manifest["counts"].get("actual_cost_usd", 0.0)))
    materialized_cost = sum(_reconstruct_spend(records_by_construct[construct_id]) for construct_id in WAVE1_CONSTRUCT_IDS)

    output_root.mkdir(parents=True, exist_ok=True)
    output_paths: dict[str, Path] = {}
    construct_manifests: list[dict[str, Any]] = []
    for construct_id in WAVE1_CONSTRUCT_IDS:
        entry = recovery_entry if construct_id == "source_reliability" else old_by_id[construct_id]
        records = records_by_construct[construct_id]
        output_path = output_root / f"{construct_id}.csv"
        output_paths[construct_id] = output_path
        _atomic_write_records(records, output_path)
        actual_usage = (
            {
                "input_tokens": source_input_tokens,
                "output_tokens": source_output_tokens,
                "total_tokens": source_total_tokens,
                "actual_cost_usd": source_spend,
                "attempt_count": source_attempt_count,
                "rejected_attempt_count": source_rejected_count,
            }
            if construct_id == "source_reliability"
            else _attempt_usage(checkpoint_usage_maps[construct_id])
        )
        details = _validate_downstream_records(
            entry,
            records,
            mode="full",
            input_price=float(
                source_manifest["runtime_settings"]["input_usd_per_million_tokens"]
                if construct_id == "source_reliability"
                else runtime_settings["input_usd_per_million_tokens"]
            ),
            output_price=float(
                source_manifest["runtime_settings"]["output_usd_per_million_tokens"]
                if construct_id == "source_reliability"
                else runtime_settings["output_usd_per_million_tokens"]
            ),
        )
        details.update({
            "actual_input_tokens": actual_usage["input_tokens"],
            "actual_output_tokens": actual_usage["output_tokens"],
            "actual_total_tokens": actual_usage["total_tokens"],
            "actual_cost_usd": actual_usage["actual_cost_usd"],
            "attempted_cost_usd": actual_usage["actual_cost_usd"],
            "accepted_record_cost_usd": _reconstruct_spend(records),
            "attempt_count": actual_usage["attempt_count"],
            "rejected_attempt_count": actual_usage["rejected_attempt_count"],
            "checkpoint_path": checkpoint_provenance[construct_id]["path"] if construct_id != "source_reliability" else recovery_info["manifest_path"],
            "checkpoint_sha256": checkpoint_provenance[construct_id]["file_sha256"] if construct_id != "source_reliability" else recovery_info["manifest_sha256"],
            "checkpoint_job_count": checkpoint_provenance[construct_id]["job_count"] if construct_id != "source_reliability" else int(source_manifest["constructs"][0].get("checkpoint_job_count", 0)),
            "output_sha256": file_sha256(output_path),
            "job_attempts": checkpoint_provenance[construct_id] if construct_id != "source_reliability" else source_manifest["constructs"][0].get("job_attempts", {}),
        })
        construct_manifests.append({
            "construct_id": construct_id,
            "wave": entry.wave,
            "spec_path": str(entry.spec_path),
            "plan_path": str(entry.plan_path),
            "spec_sha256": entry.spec_sha256,
            "source_plan_sha256": entry.source_plan_sha256,
            "plan_sha256": entry.plan_sha256,
            "provider": DEFAULT_PROVIDER,
            "requested_model": DEFAULT_MODEL,
            "reasoning_effort": DEFAULT_REASONING_EFFORT,
            "runtime_settings": dict(
                source_manifest["runtime_settings"] if construct_id == "source_reliability" else runtime_settings
            ),
            "run_mode": "full",
            "partial": False,
            "confirmatory": False,
            "scope": "downstream",
            "scope_partial": False,
            "dry_run": False,
            "record_count": details["record_count"],
            "split_counts": details["split_counts"],
            "expected_record_count": details["expected_record_count"],
            "expected_split_counts": details["expected_split_counts"],
            "request_count": details["request_count"],
            "estimated_input_tokens": details["estimated_input_tokens"],
            "estimated_output_tokens": details["estimated_output_tokens"],
            "estimated_total_tokens": details["estimated_total_tokens"],
            "estimated_cost_usd": details["estimated_cost_usd"],
            "actual_input_tokens": details["actual_input_tokens"],
            "actual_output_tokens": details["actual_output_tokens"],
            "actual_total_tokens": details["actual_total_tokens"],
            "actual_cost_usd": details["actual_cost_usd"],
            "attempted_cost_usd": details["attempted_cost_usd"],
            "accepted_record_cost_usd": details["accepted_record_cost_usd"],
            "attempt_count": details["attempt_count"],
            "rejected_attempt_count": details["rejected_attempt_count"],
            "output_path": str(output_path),
            "output_sha256": details["output_sha256"],
            "checkpoint_path": details["checkpoint_path"],
            "checkpoint_sha256": details["checkpoint_sha256"],
            "checkpoint_job_count": details["checkpoint_job_count"],
        })

    combined_path = output_root / "combined.csv"
    _atomic_write_records(all_records, combined_path)
    audit_summary_path = output_root / "audit_summary.json"
    audit_flags_path = output_root / "audit_flags.csv"
    _atomic_write_json({key: value for key, value in audit.items() if key != "flags"}, audit_summary_path)
    flag_fields = sorted({key for flag in audit["flags"] for key in flag})
    with audit_flags_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=flag_fields or ["severity", "flag_type"], lineterminator="\n")
        writer.writeheader()
        writer.writerows(audit["flags"])

    provenance = {
        "failed_run_dir": str(failed_root),
        "failed_run_state_path": str(run_state_path),
        "failed_run_state_sha256": run_state_hash,
        "failed_run_accounting": {
            "attempt_count": failed_usage["attempt_count"],
            "rejected_attempt_count": failed_usage["rejected_attempt_count"],
            "failed_request_count": int(failed_state.get("cumulative_failed_request_count", 0)),
            "actual_input_tokens": failed_usage["input_tokens"],
            "actual_output_tokens": failed_usage["output_tokens"],
            "actual_total_tokens": failed_usage["total_tokens"],
            "actual_spent_usd": failed_usage["actual_cost_usd"],
        },
        "checkpoints": checkpoint_provenance,
        "source_recovery_dir": str(source_root),
        "source_recovery_manifest_path": recovery_info["manifest_path"],
        "source_recovery_manifest_sha256": recovery_info["manifest_sha256"],
        "source_recovery_output_path": recovery_info["output_path"],
        "source_recovery_output_sha256": recovery_info["output_sha256"],
        "source_recovery_quality_gate": recovery_info["quality_gate"],
        "composition_plan_runtime_note": "The source construct uses its explicitly pinned batch-10 recovery plan hash; other constructs retain the accepted batch-20 checkpoint plan hashes.",
    }
    composition_sha256 = _canonical_sha256(provenance)
    combined_hash = file_sha256(combined_path)
    final_manifest = {
        "schema_version": "1",
        "manifest_type": "downstream_prompt_generation",
        "status": "frozen",
        "registry_path": str(registry_path),
        "waves": [1],
        "construct_ids": list(WAVE1_CONSTRUCT_IDS),
        "scope": "downstream",
        "scope_partial": False,
        "run_mode": "full",
        "partial": False,
        "frozen": True,
        "confirmatory": False,
        "composition": True,
        "provider": DEFAULT_PROVIDER,
        "requested_model": DEFAULT_MODEL,
        "reasoning_effort": DEFAULT_REASONING_EFFORT,
        "runtime_settings": {
            "composition": True,
            "completed_checkpoint_runtime_settings": dict(runtime_settings),
            "source_recovery_runtime_settings": dict(source_manifest["runtime_settings"]),
        },
        "quality_gate": {
            "wave1_composite": _validate_quality_gate(quality_gate_path, old_entries),
            "source_recovery": recovery_info["quality_gate"],
        },
        "constructs": construct_manifests,
        "audit": {key: value for key, value in audit.items() if key != "flags"},
        "audit_summary_path": str(audit_summary_path),
        "audit_flags_path": str(audit_flags_path),
        "provenance": provenance,
        "composition_sha256": composition_sha256,
        "accounting": {
            "failed_run_actual_spent_usd": failed_usage["actual_cost_usd"],
            "source_recovery_actual_spent_usd": source_spend,
            "cumulative_actual_spent_usd": failed_usage["actual_cost_usd"] + source_spend,
            "materialized_record_cost_usd": materialized_cost,
            "failed_run_attempt_count": failed_usage["attempt_count"],
            "source_recovery_attempt_count": source_attempt_count,
            "cumulative_attempt_count": failed_usage["attempt_count"] + source_attempt_count,
            "failed_run_rejected_attempt_count": failed_usage["rejected_attempt_count"],
            "source_recovery_rejected_attempt_count": source_rejected_count,
            "cumulative_rejected_attempt_count": failed_usage["rejected_attempt_count"] + source_rejected_count,
            "failed_run_failed_request_count": int(failed_state.get("cumulative_failed_request_count", 0)),
            "source_recovery_failed_request_count": source_failed_count,
            "cumulative_failed_request_count": int(failed_state.get("cumulative_failed_request_count", 0)) + source_failed_count,
            "cumulative_actual_input_tokens": failed_usage["input_tokens"] + source_input_tokens,
            "cumulative_actual_output_tokens": failed_usage["output_tokens"] + source_output_tokens,
            "cumulative_actual_total_tokens": failed_usage["total_tokens"] + source_total_tokens,
        },
        "counts": {
            "split_counts": split_counts,
            "record_count": len(all_records),
            "request_count": sum(item["request_count"] for item in construct_manifests),
            "attempt_count": failed_usage["attempt_count"] + source_attempt_count,
            "rejected_attempt_count": failed_usage["rejected_attempt_count"] + source_rejected_count,
            "actual_input_tokens": failed_usage["input_tokens"] + source_input_tokens,
            "actual_output_tokens": failed_usage["output_tokens"] + source_output_tokens,
            "actual_total_tokens": failed_usage["total_tokens"] + source_total_tokens,
            "actual_cost_usd": failed_usage["actual_cost_usd"] + source_spend,
            "materialized_record_cost_usd": materialized_cost,
        },
        "vector_reference_path": str(vector_path) if vector_path is not None else None,
        "vector_reference_sha256": file_sha256(vector_path) if vector_path is not None else None,
        "combined_path": str(combined_path),
        "combined_sha256": combined_hash,
        "manifest_path": str(output_root / "final_inventory_manifest.json"),
    }
    manifest_path = output_root / "final_inventory_manifest.json"
    _atomic_write_json(final_manifest, manifest_path)
    return final_manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Compose a provenance-verified Wave 1 downstream inventory.")
    parser.add_argument("--registry", type=Path, default=_ROOT / "configs/construct_benchmark/construct_registry_v1.json")
    parser.add_argument("--failed-run-dir", type=Path, default=DEFAULT_FAILED_RUN_DIR)
    parser.add_argument("--source-recovery-dir", type=Path, default=DEFAULT_SOURCE_RECOVERY_DIR)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--vector-reference", type=Path, default=DEFAULT_VECTOR_REFERENCE)
    parser.add_argument("--skip-vector-reference", action="store_true")
    parser.add_argument("--quality-gate-file", type=Path, default=DEFAULT_QUALITY_GATE)
    parser.add_argument("--source-quality-gate-file", type=Path, default=DEFAULT_SOURCE_QUALITY_GATE)
    parser.add_argument("--old-batch-size", type=int, default=20)
    parser.add_argument("--old-max-output-tokens", type=int, default=12_000)
    parser.add_argument("--recovery-batch-size", type=int, default=20)
    parser.add_argument("--recovery-max-output-tokens", type=int, default=30_000)
    args = parser.parse_args()
    manifest = compose_downstream_inventory(
        registry_path=args.registry,
        failed_run_dir=args.failed_run_dir,
        source_recovery_dir=args.source_recovery_dir,
        output_dir=args.output_dir,
        vector_reference=None if args.skip_vector_reference else args.vector_reference,
        quality_gate_file=args.quality_gate_file,
        source_quality_gate_file=args.source_quality_gate_file,
        old_batch_size=args.old_batch_size,
        old_max_output_tokens=args.old_max_output_tokens,
        recovery_batch_size=args.recovery_batch_size,
        recovery_max_output_tokens=args.recovery_max_output_tokens,
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
